/**
 * Created by Administrator on 2017/11/8.
 */
export default {
    cell_use_arrow: true,
    cell_height: 90,
    cell_left_txt: '',
    cell_left_txt_sub: '',
    cell_background_color: '',
    cell_left_color: '',
    cell_left_color_sub: '',
    cell_left_size: 28,
    cell_left_size_sub: 28,
    cell_left_width: '',
    cell_right_txt: '',
    cell_right_color: '#000',
    cell_right_size: 28,
    cell_left_src: '',
    cell_left_src_mar_left: '',
    cell_left_src_mar_right: '',
    cell_left_src_size: [36,36],
    cell_padding_left: 0,
    cell_padding_right: 0,
    cell_inner_padding_left: 0,
    cell_inner_padding_right: 0,
    cell_border_width: 2,
    cell_border_color: '#ddd',
    cell_inner_border_width: 0,
    cell_inner_border_color: '#ddd',
    cell_right_src: '',
    cell_right_src_size: [36,36],
    cell_right_src_mar_left: 0,
    cell_right_src_mar_right: 0,
    cell_use_input: false,
    cell_input_disabled: false,
    cell_input_type: 'text',
    cell_input_placeholder: '请输入',
    cell_input_max: '',
    cell_right_text_align: 'right',
    cell_input_mar_top: 0,
    cell_left_sub_mar_top: 0,
}